variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

build:
  stage: build
  image: 3.8.6-openjdk-18
  script:
    - mvn clean install -DskipTests
  artifacts:
    paths:
      - target/
  cache:
    paths:
      - specmaker-api/.m2/


push-docker-hub:
  stage: deploy
  image: docker:18.09.8-dind
  services:
    - docker:18.09.8-dind
  before_script:    
    - apk add --update --upgrade curl && rm -rf /var/cache/apk/*
  script:
    - export BUILD_TAG=$CI_COMMIT_REF_NAME-1.1.$CI_PIPELINE_IID
    - docker login -u sescsp -p 4d52970a-7732-4e21-85c1-41d9683d7287
    - docker build -t sescsp/specmaker:$BUILD_TAG .
    - docker push sescsp/specmaker:$BUILD_TAG

stages:
  - build
  - deploy

