variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

build:
  stage: build
  image: maven:3.8.6-openjdk-18-slim
  script:
    - mvn clean install -DskipTests
  artifacts:
    paths:
      - target/
  cache:
    paths:
      - specmaker-api/.m2/

push-docker-hub:
  stage: deploy
  image: docker:18.09.8-dind
  services:
    - docker:18.09.8-dind
  before_script:    
    - apk add --update --upgrade curl && rm -rf /var/cache/apk/*
  script:
    - export BUILD_TAG=$CI_DEFAULT_BRANCH-1.1.$CI_PIPELINE_IID
    - docker login -u henriquealle -p hY6jLyNQAVww5vu
    - docker build -t henriquealle/specmaker:$BUILD_TAG .
    - docker push henriquealle/specmaker:$BUILD_TAG

stages:
  - build
  - deploy