azure:
  api:
    token: ${AZURE_DEVOPS_TOKEN}
    mainFolderId: ${MAIN_QUERY_FOLDER}
    repositorio: ${PROJETO_AZURE_DEVOPS}
    baseUrl: ${AZURE_DEVOPS_BASE_URL}
    apiVersion: ${AZURE_DEVOPS_API_VERSION}