azure:
  api:
    token: ${AZURE_DEVOPS_TOKEN:p5nowls65penhmar47dlropr7mazdjkpaoopxigylgmcv2shzhyq}
    mainFolderId: ${MAIN_QUERY_FOLDER:5f6919de-2cf1-41cd-907c-f801cb77f93f}
    repositorio: ${PROJETO_AZURE_DEVOPS:spec-maker}
    baseUrl: ${AZURE_DEVOPS_BASE_URL:https://dev.azure.com/henriquealle}
    apiVersion: ${AZURE_DEVOPS_API_VERSION:7.1-preview.2}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sys}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

aws:
  s3:
    accessKeyId: ${AWS_S3_ACCESS_KEY}
    secretKey: ${AWS_S3_SECRET_KEY}
    bucketName: ${AWS_S3_BUCKET_NAME:specmaker}
  region: ${AWS_REGION:us-west-2}

auditoria:
  folderName: ${AUDITORIA_FOLDER_NAME:~/auditoria/}
